### ISSUE TITLE
Phone number on other profiles matches local user

### ISSUE THREAD

**Issue by lmay1231** [coopersully/law_app#8]
It seems as though the phone number listed on the expanded view of a profile is the same as the one of the local user. Hard to verify since they have been censored with asterisks but they all start with the same area code as my phone number. @LilyBouldin would you be able to test to see if the area codes of other phone numbers stay as "205" or change to your phone number area code?

**Comment by AndrewDeSimone** [comment]
All the test users have been given a Birmingham area code followed by 'xxx-xxxx'.  When I use my account (201 area code) it displays other users with the phone number "205-xxx-xxxx"
